### PR TITLE
Adopts shared linter rules

### PR DESCRIPTION
**Pull request by klebba**
One new violation:

```
~/x-element.js
  1328:53  warning  Function declared in a loop contains unsafe references to variable(s) 'node'  no-loop-func

✖ 1 problem (0 errors, 1 warning)
```

### CODE REVIEW

**Comment by klebba** [comment]
@theengineear how do you recommend I address the `no-loop-func` violation? I could ignore it or rework it (could use your help with that)

**Comment by theengineear** [comment]
Can you just change that `find` function from:

```js
    const find = path => {
      let node = content;
      for (const index of path) {
        node = Template.#setIfMissing(lookup, node, () => node.childNodes)[index];
      }
      return node;
    };
```

to

```js
    const find = path => {
      let node = content;
      for (const index of path) {
        const ref = node;
        node = Template.#setIfMissing(lookup, node, () => ref.childNodes)[index];
      }
      return node;
    };
```

**Comment by klebba** [comment]
Thanks for the explainer! Fixt.

**Review by theengineear — APPROVED** [review]
LGTM!

**Pull request merged**
